env:
  global:
   # Required for clang.
   - CXXFLAGS="-fno-fast-math"

branches:
  except:
  - /^v[0-9]/

language: cpp

matrix:
  include:
  - os: linux
    compiler: gcc
  - os: osx
    compiler: clang

sudo: false
dist: trusty

addons:
  apt:
    packages:
    - libboost-dev
    - libboost-date-time-dev
    - libboost-thread-dev
    - libjpeg8-dev
    - libopenexr-dev
    - libpng12-dev
    - libtiff4-dev
    - libsdl2-dev
    - zlib1g-dev

install:
- cd unix
- chmod +x prebuild3rdparty.sh && ./prebuild3rdparty.sh
- cd ..
- ./configure COMPILED_BY="Travis CI by Trevor SANDY <trevor.sandy@gmail.com> for LPub3D." --prefix="$(pwd)/lpub3d_linux_3rdparty" LPUB3D_3RD_PARTY="yes" --with-libsdl2 --enable-watch-cursor
- make check
- make install

script:
- true

notifications:
  email:
    recipients:
    - ${NOTIFICATION_EMAIL}
    on_success: change
    on_failure: always
