language: cpp
cache: ccache
sudo: false
dist: trusty

git:
  depth: 200

branches:
  only:
  - lpub3d/raytracer-cui

addons:
  apt:
    packages:
    - libboost-dev
    - libboost-date-time-dev
    - libboost-thread-dev
    - libjpeg8-dev
    - libopenexr-dev
    - libpng12-dev
    - libtiff4-dev
    - libsdl2-dev
    - zlib1g-dev

matrix:
  fast_finish: true
  include:
  - os: linux
    compiler: gcc
  - os: osx
    compiler: clang

before_install:
  # Skip build if the commit message contains [skip travis] or [travis skip]
  - >
      echo "$TRAVIS_COMMIT_MESSAGE"
      | grep -E  '\[(skip travis|travis skip)\]'
      && echo "[skip travis] detected, exiting."
      && exit 0 || true
  # Build package if commit message contains [build pkg]
  - >
      echo "$TRAVIS_COMMIT_MESSAGE"
      | grep -E  '\[build pkg\]'
      && echo "[build pkg] detected."
      && export POV_BUILD_PKG=yes || true
  # Build and deploy package if commit message contains [deploy pkg]
  - >
      echo "$TRAVIS_COMMIT_MESSAGE"
      | grep -E  '\[deploy pkg\]'
      && echo "[deploy pkg] detected."
      && export POV_BUILD_PKG=yes
      && export POV_DEPLOY_PKG=yes || true
  # Update repository index and download package dependencies/docker-engine if required
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then
      sudo apt-get update -qq;
      export POV_REPO_NAME=lpub3d_linux_3rdparty;
    else
      brew update;
      brew install ccache;
      export CXXFLAGS="-fno-fast-math";
      export PATH="/usr/local/opt/ccache/libexec:$PATH";
      export POV_REPO_NAME=lpub3d_macos_3rdparty;
    fi

install:
  - cd unix
  - chmod +x prebuild3rdparty.sh && ./prebuild3rdparty.sh
  - cd ..
  - ./configure COMPILED_BY="Trevor SANDY <trevor.sandy@gmail.com> using Travis CI for LPub3D." --prefix="$(pwd)/lpub3d_linux_3rdparty" LPUB3D_3RD_PARTY="yes" --with-libsdl2 --enable-watch-cursor
  - make check
  - make install

script:
  - true

before_deploy:
  # create a tarball of the lpub3d_linux_3rdparty folder
  - if [ "$POV_BUILD_PKG" = "yes" ]; then
      if [ -d ${POV_REPO_NAME} ]; then
        tar -czf ${POV_REPO_NAME}.tar.gz ${POV_REPO_NAME} && echo "Tarball ${POV_REPO_NAME}.tar.gz created.";
      fi;
    fi

deploy:
  provider: releases
  api_key:
    secure: GRl0LOJ8M5ow1qik8t2+tJsqMDo53v/TRfxprWg5C+3DR3ny/CgR5mODMtpR4LgSyMeD5yhGovxHAbzgUyutne9PT0BagI8zdt/ZMqcLnvPQyzJlhfy3t2TVcJRoVXcoUUF0ZJHrpr9WD8C7xnjMp7w/j+HThQuX+8CD3gCwZhYkDRuNgtJY/PT+nwITjC4WJuF0xxYOyLJROebQZ1LJ24HY0zVtg+JJZPslkQHgoBg/ozO8JNXgYaYe3VgcyQSnUMqE/SjMBGYMR9RlNwYXCJLeYHiY3fej33z7UPZOH/kPQ8RhKpJi9qqOTtYj38dTxmpiJjOJ4SyeKXvsyymc5ekwSdlJe6rVWKKAXFMegH/4i3Nk8HKmfxMPLklprusFEMQo2CdA5UeNRuWJ/HfDpywbQwFLC6ThNZcS6wqOqf2Rzy6QRNFWlH9eJoiSMyQRVTFGwQ3bf2MXXJSloFuxRpGYoejWt36O+rNZnTR6+Xz1r2KyaaFizCGen082klzmfdoCl0mh+m9Jix7ypzgNBKISFI5DTbjr6Qt+D5dVdp5PWGBAbhTd6JtcG64P9fDUWq5X9ypFj6Jb1626sHFlYQKCSX+lEpjbd4UTSbTxO35NMTO1g90xKMJeIpvsCwm9DcWl+jGmt9cwSHxTQuWkeEaUcoywYvA4kTjIpDuIaR8=
  file: ${POV_REPO_NAME}.tar.gz
  overwrite: true
  skip_cleanup: true
  on:
    repo: trevorsandy/povray
    branch: lpub3d/raytracer-cui
    condition: $POV_DEPLOY_PKG = yes

notifications:
  email:
    on_success: never
    on_failure: always
