version: 'LPub3D-Trace-CUI-AV-{build}'

clone_folder: c:\projects\povray

branches:
  only:
   - lpub3d/raytracer-cui

image: Visual Studio 2017

shallow_clone: true

matrix:
  fast_finish: true

# Build package if commit message contains [build pkg]
# Deploy package if commit message contains [deploy pkg]
init:
 - ps: write-host "Building LPub3D-Trace-CUI x86 and x86_64 architectures..."
 - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
 - ps: |
      If ($env:APPVEYOR_REPO_COMMIT_MESSAGE.ToLower().Contains("[build pkg]")) {
        write-host "[build pkg] detected."
        $env:POV_BUILD_PKG = "yes"
        $env:POV_REPO_NAME = "lpub3d_windows_3rdparty"
        If ($env:APPVEYOR_REPO_COMMIT_MESSAGE.ToLower().Contains("[deploy pkg]")) {
          write-host "[deploy pkg] detected."
          $env:POV_DEPLOY_PKG = $true
        }
      }
 - ps: |
      If ($env:APPVEYOR_REPO_COMMIT_MESSAGE.ToLower().Contains("[deploy pkg]")) {
        write-host "[deploy pkg] detected."
        $env:POV_DEPLOY_PKG = $true
      }

build_script:
 - ps: |
      If ($env:POV_BUILD_PKG -eq "yes") {
        cmd.exe /c windows\vs2015\autobuild -allcui -allins
      } Else {
        cmd.exe /c windows\vs2015\autobuild x86 -chk
        cmd.exe /c windows\vs2015\autobuild x86_64 -chk
      }

test: off

after_build:
 - ps: |
      If (($env:POV_DEPLOY_PKG -eq "yes") -and (Test-Path .\$env:APPVEYOR_BUILD_FOLDER\$env:POV_REPO_NAME\lpub3d_trace_cui-3.8\bin\x86_64\lpub3d_trace_cui64.exe)) {
        bash -lc "tar -czf ${POV_REPO_NAME}.tar.gz ${POV_REPO_NAME} && echo Tarball ${POV_REPO_NAME}.tar.gz created."
        If ($env:POV_BUILD_PKG -eq "yes") {
          $root = Resolve-Path .\$env:APPVEYOR_BUILD_FOLDER
          [IO.Directory]::GetFiles($root.Path, '*.tar.gz', 'TopDirectoryOnly') | % { Push-AppveyorArtifact $_ -FileName $_.Substring($root.Path.Length + 1) -DeploymentName $env:POV_REPO_NAME }
        }
      }

deploy:
 - provider: GitHub
   description: ''
   auth_token:
     secure: rnf4qpF81ISjm8q13OgkAaoKZReXpjODhU9fbGFMhMydHrda1ezLubGXRU9OKGu4
   artifact: $(POV_REPO_NAME).tar.gz
   prerelease: true
   force_update: true
   on:
    branch: lpub3d/raytracer-cui
    pov_deploy_pkg: true
