version: 'LPub3D-Trace-CUI-AV-{build}'

clone_folder: c:\projects\povray

shallow_clone: true

branches:
  only:
   - lpub3d/raytracer-cui

skip_commits:
  files:
   - unix/
   - vfe/unix/

image: Visual Studio 2017

matrix:
  fast_finish: true

environment:
  POV_DIST_DIR: lpub3d_windows_3rdparty
  POV_DIST_DIR_PATH: $(APPVEYOR_BUILD_FOLDER)\$(POV_DIST_DIR)

init:
 - ps: write-host "Building LPub3D-Trace-CUI x86 and x86_64 architectures..."
 - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
 - ps: |
      If ($env:APPVEYOR_REPO_COMMIT_MESSAGE.ToLower().Contains("[build pkg]")) {
        write-host "[build pkg] detected."
        $env:POV_BUILD_PKG = "yes"
      }
 - ps: |
      If ($env:APPVEYOR_REPO_COMMIT_MESSAGE.ToLower().Contains("[deploy pkg]")) {
        write-host "[deploy pkg] detected."
        $env:POV_BUILD_PKG = "yes"
        $env:POV_DEPLOY_PKG = $true
      }

build_script:
 - ps: |
      write-host "  Build directory.....[$env:POV_DIST_DIR_PATH]"
      cd windows\vs2015; write-host "  Working Directory...[$PWD]"
      If ($env:POV_BUILD_PKG -eq "yes") {
        cmd.exe /c autobuild.cmd -allcui -allins -chk
        $env:POV_ARTEFACT_ITEM_COUNT = (Get-ChildItem -Path $env:POV_DIST_DIR_PATH -Recurse).count
        write-host "`n  Artifact count....[$env:POV_ARTEFACT_ITEM_COUNT]"
      } Else {
        cmd.exe /c autobuild.cmd -allcui -chk
      }

test: off

after_build:
 - ps: |
      If (($env:POV_BUILD_PKG -eq "yes") -and ([int]$env:POV_ARTEFACT_ITEM_COUNT -gt 50)){
        cd $env:APPVEYOR_BUILD_FOLDER; write-host "Creating single tarball artefact from ./${POV_DIST_DIR}..."
        bash -lc "tar -czvf lpub3d_windows_3rdparty.tar.gz ./lpub3d_windows_3rdparty && echo Tarball lpub3d_windows_3rdparty.tar.gz created."
        $root = Resolve-Path $env:APPVEYOR_BUILD_FOLDER; [IO.Directory]::GetFiles($root.Path, '*.tar.gz', 'TopDirectoryOnly') | % { Push-AppveyorArtifact $_ -FileName $_.Substring($root.Path.Length + 1) -DeploymentName $env:POV_DIST_DIR}
      }

deploy:
 - provider: GitHub
   repository: trevorsandy/povray
   description: 'LPub3D-Trace-CUI - Windows archive package of LPub3D image renderer based on POV-Ray'
   auth_token:
     secure: rnf4qpF81ISjm8q13OgkAaoKZReXpjODhU9fbGFMhMydHrda1ezLubGXRU9OKGu4
   release: $(POV_DIST_DIR)
   artifact: $(POV_DIST_DIR).tar.gz
   prerelease: true
   force_update: true
   on:
    branch: lpub3d/raytracer-cui
    pov_deploy_pkg: true
