# Build and check LPub3D-Trace (POV-Ray) x86 and x86_64 architectures unsing MSBuild
# Trevor SANDY <trevor.sandy@gmail.com>
# Last Update: June 10, 2021
# Copyright (c) 2017 - 2022 by Trevor SANDY
#

# The following variables can be set to true from
# AppVeyor Site->Project->Settings->Environment Variables
#
# POV_SKIP_APPVEYOR_VAR     ; skip AppVeyor build


version: 'LPub3D-Trace-CUI-AV-{build}'

clone_folder: c:\projects\povray

shallow_clone: true

branches:
  only:
   - lpub3d/raytracer-cui

skip_commits:
  files:
   - unix/
   - vfe/unix/

image: Visual Studio 2019

matrix:
  fast_finish: true

environment:
  LP3D_3RD_DIST_DIR: lpub3d_windows_3rdparty
  LP3D_DIST_DIR_PATH: $(APPVEYOR_BUILD_FOLDER)\$(LP3D_3RD_DIST_DIR)

init:
 - ps: |
      If ($env:POV_SKIP_APPVEYOR_VAR -eq "true") {
         write-host "Skip Appveyor build detected in environment variable."
         Exit-AppveyorBuild
      }
 - ps: write-host "Building LPub3D-Trace-CUI x86 and x86_64 architectures..."
 - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
 - ps: |
      If ($env:APPVEYOR_REPO_COMMIT_MESSAGE.ToLower().Contains("[build pkg]")) {
        write-host "[build pkg] detected."
        $env:POV_BUILD_PKG = "yes"
      }
 - ps: |
      If ($env:APPVEYOR_REPO_COMMIT_MESSAGE.ToLower().Contains("[deploy pkg]")) {
        write-host "[deploy pkg] detected."
        $env:POV_BUILD_PKG = "yes"
        $env:POV_DEPLOY_PKG = $true
      }

build_script:
 - ps: |
      write-host "  Distribution directory.....[$env:LP3D_DIST_DIR_PATH]"
      cd windows\vs2015; write-host "  Working Directory..........[$PWD]"
      If ($env:POV_BUILD_PKG -eq "yes") {
        cmd.exe /c autobuild.cmd -allcui -allins -chk -minlog 2`>`&1
        $env:POV_ARTEFACT_ITEM_COUNT = (Get-ChildItem -Path $env:LP3D_DIST_DIR_PATH -Recurse).count
        write-host "`n  Artifact count....[$env:POV_ARTEFACT_ITEM_COUNT]"
      } Else {
        cmd.exe /c autobuild.cmd -allcui -chk -minlog 2`>`&1
      }

test: off

after_build:
 - ps: |
      If (($env:POV_BUILD_PKG -eq "yes") -and ([int]$env:POV_ARTEFACT_ITEM_COUNT -gt 50)){
        cd $env:APPVEYOR_BUILD_FOLDER; write-host "Creating zip archive artefact from ./$env:LP3D_3RD_DIST_DIR..."
        7z a -tzip $env:LP3D_3RD_DIST_DIR $env:LP3D_3RD_DIST_DIR | Select-String -Pattern '(^Creating)|(^Everything)' -CaseSensitive; write-host "Zip archive $env:LP3D_3RD_DIST_DIR.zip created."
        $root = Resolve-Path $env:APPVEYOR_BUILD_FOLDER; [IO.Directory]::GetFiles($root.Path, '*.zip', 'TopDirectoryOnly') | % { Push-AppveyorArtifact $_ -Type zip -FileName $_.Substring($root.Path.Length + 1) -DeploymentName $env:LP3D_3RD_DIST_DIR}
      }

deploy:
 - provider: GitHub
   repository: trevorsandy/povray
   description: 'LPub3D-Trace-CUI - Windows archive package of LPub3D image renderer based on POV-Ray'
   auth_token:
     secure: rnf4qpF81ISjm8q13OgkAaoKZReXpjODhU9fbGFMhMydHrda1ezLubGXRU9OKGu4
   release: $(LP3D_3RD_DIST_DIR)
   artifact: $(LP3D_3RD_DIST_DIR).zip
   prerelease: true
   force_update: true
   on:
    branch: lpub3d/raytracer-cui
    pov_deploy_pkg: true
