version: 'LPub3D-Trace-CUI-AV-{build}'

clone_folder: c:\projects\povray

branches:
  only:
   - lpub3d/raytracer-cui

image: Visual Studio 2017

shallow_clone: true

matrix:
  fast_finish: true

# Build package if commit message contains [build pkg]
# Deploy package if commit message contains [deploy pkg]
init:
 - ps: write-host "Building LPub3D-Trace-CUI x86 and x86_64 architectures..."
 - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
 - ps: |
      If ($env:APPVEYOR_REPO_COMMIT_MESSAGE.ToLower().Contains("[build pkg]")) {
        write-host "[build pkg] detected."
        $env:POV_BUILD_PKG = "yes"
      }
 - ps: |
      If ($env:APPVEYOR_REPO_COMMIT_MESSAGE.ToLower().Contains("[deploy pkg]")) {
        write-host "[deploy pkg] detected."
        $env:POV_BUILD_PKG = "yes"
        $env:POV_DEPLOY_PKG = $true
      }

before_build:
 - ps: $env:POV_DIST_DIR = "$PWD\lpub3d_windows_3rdparty"

build_script:
 - ps: |
      write-host "Working Directory: $PWD"
      If ($env:POV_BUILD_PKG -eq "yes") {
        cmd.exe /c autobuild.cmd -allcui -allins
      } Else {
        cmd.exe /c autobuild.cmd x86 -chk
        cmd.exe /c autobuild.cmd x86_64 -chk
      }
 - ps: $env:POV_ARTEFACTS = Get-ChildItem -Path $env:POV_DIST_DIR -Recurse
 - ps: write-host "   ARTEFACT COUNT....[$env:POV_ARTEFACTS.count]"

test: off

after_build:
 - ps: |
      If (($env:POV_BUILD_PKG -eq "yes") -and ($env:POV_ARTEFACTS.count -gt 50)) {
        write-host "Creating single tarball artefact..."
        bash -lc "tar -czf ${POV_DIST_DIR}.tar.gz ${POV_DIST_DIR} && echo Tarball ${POV_DIST_DIR}.tar.gz created."
        $root = Resolve-Path .\$env:APPVEYOR_BUILD_FOLDER; [IO.Directory]::GetFiles($root.Path, '*.tar.gz', 'TopDirectoryOnly') | % { Push-AppveyorArtifact $_ -FileName $_.Substring($root.Path.Length + 1) -DeploymentName $env:POV_DIST_DIR }
      }

deploy:
 - provider: GitHub
   description: 'LPub3d-Trace-CUI - Customized POV-Ray for LPub3D'
   auth_token:
     secure: rnf4qpF81ISjm8q13OgkAaoKZReXpjODhU9fbGFMhMydHrda1ezLubGXRU9OKGu4
   artifact: $(POV_DIST_DIR).tar.gz
   prerelease: true
   force_update: true
   on:
    branch: lpub3d/raytracer-cui
    pov_deploy_pkg: true
