# LPub3D Raytracer-cui build actions
# Trevor SANDY <trevor.sandy@gmail.com>
# Last Update: September 10, 2022
#
name: 'Sanity-Check Working Tree'
description: 'Verify that working tree (and index) of repository is "clean"'
runs:
  using: composite
  steps:
  - shell: bash
    run: |
      changed=$( git status --porcelain )
      if test -z "$changed" ; then
        echo "No unexpected changes to the working tree found."
        exit 0
      fi
      untracked=$( echo "$changed" | egrep '^[?]' || true )
      changed=$( echo "$changed" | egrep '^[^?]' || true )
      if test -n "$untracked" ; then
        echo "::error::Build process adds files not covered by .gitignore."
      fi
      if test -n "$changed" ; then
        echo "::error::Build process tampers with tracked files."
      fi
      echo "::group::Offending files:"
      if test -n "$untracked" ; then
        echo "Added files:"
        echo "$untracked"
      fi
      if test -n "$changed" ; then
        echo "Changed files:"
        echo "$changed"
      fi
      echo "::endgroup::"
      exit 1
