# LPub3D Raytracer-cui build actions
# Trevor SANDY <trevor.sandy@gmail.com>
# Last Update: May 22, 2022
#
name: 'Build POV-Ray CLI for Windows Binary'
description: 'Build POV-Ray CLI for Windows Binary'

inputs:
  pov-ray-is-autobuild:
    description: 'POV_RAY_IS_AUTOBUILD value'
    required: true
    default: '1'
  pov-ray-build-id:
    description: 'POV_RAY_BUILD_ID value'
    required: true
  version-base:
    description: 'VERSION_BASE value'
    required: true
  built-by:
    description: 'BUILT_BY value'
    required: true
    default: 'GitHub for LPub3D'
  solution:
    description: 'subdirectory of `windows` in which `povray.sln` is located'
    required: true
  configuration:
    description: 'solution configuration to build'
    required: false
    default: 'Release'
  platform:
    description: 'solution platform to build'
    required: false
    default: 'x64'
  toolset:
    description: 'Platform toolset version'
    required: false
    default: 'v140'
  msbuild-options:
    description: 'additional MSBuild options'
    required: false
    default: ''

runs:
  using: composite
  steps:
  - shell: pwsh
    run: |
      $env:PovBuildDefs  = 'POV_RAY_IS_AUTOBUILD=${{ inputs.pov-ray-is-autobuild }};'
      $env:PovBuildDefs += 'POV_RAY_BUILD_ID="${{ inputs.pov-ray-build-id }}";'
      $env:PovBuildDefs += 'VERSION_BASE="${{ inputs.version-base }}";'
      $env:PovBuildDefs += 'BUILT_BY="${{ inputs.built-by }}";'
      $env:PovBuildDefs += '_CONSOLE=1";'
      msbuild `
        /t:Rebuild /m `
        /p:Configuration=${{ inputs.configuration }} `
        /p:Platform=${{ inputs.platform }} `
        /p:PlatformToolset=${{ inputs.toolset }} `
        ${{ inputs.msbuild-options }} `
        windows/${{ inputs.solution }}/console.vcxproj `
        /clp:ErrorsOnly /nologo
