# LPub3D Raytracer-cui build actions
# Trevor SANDY <trevor.sandy@gmail.com>
# Last Update: August 29, 2023
#
name: 'Build POV-Ray CLI for Windows Binary'
description: 'Build POV-Ray CLI for Windows Binary'

inputs:
  pov-ray-is-autobuild:
    description: 'POV_RAY_IS_AUTOBUILD value'
    required: true
    default: '1'
  pov-ray-build-id:
    description: 'POV_RAY_BUILD_ID value'
    required: true
  version-base:
    description: 'VERSION_BASE value'
    required: true
  built-by:
    description: 'BUILT_BY value'
    required: true
    default: 'GitHub for LPub3D'
  solution:
    description: 'Subdirectory of `windows` in which `povray.sln` is located - vs2015'
    required: true
  configuration:
    description: 'Solution configuration to build - Release, Release-SSE2'
    required: false
    default: 'Release'
  platform:
    description: 'Solution platform to build - x64, Win32'
    required: false
    default: 'x64'
  toolset:
    description: 'Platform toolset version - v142(x64), v140(Win32)'
    required: false
    default: 'v142'
  compatibility:
    description: 'Toolset compatibility -e.g. _xp(Win32)'
    required: false
    default: ''    
  msbuild-options:
    description: 'Additional MSBuild options -e.g. /p:TargetUniversalCRTVersion=10.0.10586.0(Win32)'
    required: false
    default: ''

runs:
  using: composite
  steps:
  - shell: pwsh
    run: |
      $env:PovBuildDefs  = 'POV_RAY_IS_AUTOBUILD=${{ inputs.pov-ray-is-autobuild }};'
      $env:PovBuildDefs += 'POV_RAY_BUILD_ID="${{ inputs.pov-ray-build-id }}";'
      $env:PovBuildDefs += 'VERSION_BASE="${{ inputs.version-base }}";'
      $env:PovBuildDefs += 'BUILT_BY="${{ inputs.built-by }}";'
      $env:PovBuildDefs += '_CONSOLE=1";'
      msbuild `
        /t:Rebuild /m `
        /p:Configuration=${{ inputs.configuration }} `
        /p:Platform=${{ inputs.platform }} `
        /p:PlatformToolset=${{ inputs.toolset }}${{ inputs.compatibility }} `
        ${{ inputs.msbuild-options }} `
        windows/${{ inputs.solution }}/console.vcxproj `
        /clp:ErrorsOnly /nologo
