# LPub3D Raytracer-cui build actions
# Trevor SANDY <trevor.sandy@gmail.com>
# Last Update: July 17, 2025
#
name: 'Build POV-Ray CLI for Windows Binary'
description: 'Build POV-Ray CLI for Windows Binary'

inputs:
  pov-ray-is-autobuild:
    description: 'POV_RAY_IS_AUTOBUILD value'
    required: true
    default: '1'
  pov-ray-build-id:
    description: 'POV_RAY_BUILD_ID value'
    required: true
  version-base:
    description: 'VERSION_BASE value'
    required: true
  built-by:
    description: 'BUILT_BY value'
    required: true
    default: 'GitHub for LPub3D'
  solution:
    description: 'Subdirectory of `windows` in which `povray.sln` is located - vs2015'
    required: false
    default: 'vs2015'
  configuration:
    description: 'Solution configuration to build - Release, Release-SSE2, Release-AVX512'
    required: false
    default: 'Release'
  platform:
    description: 'Solution platform to build - x64, Win32, ARM64'
    required: false
    default: 'x64'
  toolset:
    description: 'Platform toolset version - v143(x64), v142(Win32)'
    required: false
    default: 'v143'
  vcvarsver:
    description: 'Microsoft C++ runtime library version'
    required: false
    default: 14.4
  mscversion:
    description: 'Microsoft C++ compiler version'
    required: false
    default: 1944
  compatibility:
    description: 'Toolset compatibility -e.g. _xp(Win32)'
    required: false
    default: ''
  msbuild-options:
    description: 'Additional MSBuild options -e.g. /p:TargetUniversalCRTVersion=10.0.10586.0(Win32)'
    required: false
    default: ''

runs:
  using: composite
  steps:
  - name: VC ${{ inputs.toolset }} Build Tools
    if: ${{ inputs.platform == 'Win32' }} && ${{ inputs.toolset == 'v141' }}
    run: |
      Set-Location "C:\Program Files (x86)\Microsoft Visual Studio\Installer\"
      $InstallPath = "C:\Program Files\Microsoft Visual Studio\2022\Enterprise"
      $ComponentsToAdd= @("Microsoft.VisualStudio.Component.VC.${{ inputs.toolset }}.x86.x64")
      [string]$WorkloadArgs = $ComponentsToAdd | ForEach-Object {" --add " +  $_}
      $Arguments = ('/c', "vs_installer.exe", 'modify', '--installPath', "`"$InstallPath`"",$WorkloadArgs, '--quiet', '--norestart', '--nocache')
      # should be run twice
      $Process = Start-Process -FilePath cmd.exe -ArgumentList $Arguments -Wait -PassThru -WindowStyle Hidden
      $Process = Start-Process -FilePath cmd.exe -ArgumentList $Arguments -Wait -PassThru -WindowStyle Hidden
    shell: pwsh
  - name: Windows 8.1 SDK
    if: ${{ inputs.platform == 'Win32' }} && ${{ inputs.toolset == 'v141' }}
    run: |
      Invoke-WebRequest -Method Get -Uri https://go.microsoft.com/fwlink/p/?LinkId=323507 -OutFile sdksetup.exe -UseBasicParsing
      Start-Process -Wait sdksetup.exe -ArgumentList "/q", "/norestart", "/features", "OptionId.WindowsDesktopSoftwareDevelopmentKit"
    shell: pwsh
  - name: Build ${{ inputs.platform }}
    run: |
      if ( '${{ inputs.platform }}' -eq 'ARM64' )
      {
        if (Test-Path env:LIBPATH) {
          Write-Host "ARM64 environment variables already set."
        } else {
          Push-Location "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build"
          cmd /c "vcvarsamd64_arm64.bat -vcvars_ver=${{ inputs.vcvarsver }}&set" |
            ForEach-Object {
              If ($_ -match "=") {
                $v = $_.split("="); Set-Item -Force -Path "ENV:\$($v[0])" -Value "$($v[1])"
              }
            }
          Write-Host ${{ inputs.mscversion }} 6>&1 | Out-File $env:TEMP\settings.c
          cl.exe -Bv -EP $env:TEMP\settings.c | Out-Null
          Pop-Location
        }
      }
      $env:PovBuildDefs  = 'POV_RAY_IS_AUTOBUILD=${{ inputs.pov-ray-is-autobuild }};'
      $env:PovBuildDefs += 'POV_RAY_BUILD_ID="${{ inputs.pov-ray-build-id }}";'
      $env:PovBuildDefs += 'VERSION_BASE="${{ inputs.version-base }}";'
      $env:PovBuildDefs += 'BUILT_BY="${{ inputs.built-by }}";'
      $env:PovBuildDefs += '_CONSOLE=1";'
      msbuild `
        /t:Rebuild /m `
        /p:Configuration=${{ inputs.configuration }} `
        /p:Platform=${{ inputs.platform }} `
        /p:PlatformToolset=${{ inputs.toolset }}${{ inputs.compatibility }} `
        ${{ inputs.msbuild-options }} `
        windows/${{ inputs.solution }}/console.vcxproj `
        /clp:ErrorsOnly /nologo
    shell: pwsh
