# LPub3D Raytracer-cui build actions
# Trevor SANDY <trevor.sandy@gmail.com>
# Last Update: September 12, 2024
#
name: 'LPub3D Trace CUI Builds'

on:
  workflow_dispatch:
  push:
    branches:
      - lpub3d/raytracer-cui
    paths-ignore: [ 'distribution/**', 'doc/**', 'source-doc/**' ]
  pull_request:
    branches:
      - lpub3d/raytracer-cui
    paths-ignore: [ 'distribution/**', 'doc/**', 'source-doc/**' ]

jobs:
  build_unix:
    # if: ${{ false }} # uncomment to disable
    name: 'build-${{ matrix.os }} ${{ matrix.c-compiler }}'

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04, macos-13]
        c-compiler: [gcc, clang]
        exclude:
        - os: macos-13
          c-compiler: gcc
        - os: ubuntu-22.04
          c-compiler: clang
        include:
        # os-specific
        - os: ubuntu-22.04
        - os: macos-13
        # compiler-specific
        - c-compiler: gcc
          cxx-compiler: g++
        - c-compiler: clang
          cxx-compiler: clang++

    steps:

    - name: 'Matrix Diagnostics'
      shell: bash
      run: |
        echo '${{ toJSON(matrix) }}'
        ${{matrix.c-compiler}} --version

    - name: 'Check out Repository'
      uses: actions/checkout@v4

    - name: 'Install Prerequisites'
      uses: trevorsandy/povray/.github/actions/unix_getlibs@gh-actions-raytracer-v4

    - name: 'Prebuild'
      uses: trevorsandy/povray/.github/actions/unix_prebuild@gh-actions-raytracer-v4

    - name: 'Configure'
      uses: trevorsandy/povray/.github/actions/unix_configure@gh-actions-raytracer-v4
      with:
        c-compiler: ${{ matrix.c-compiler }}
        cxx-compiler: ${{ matrix.cxx-compiler }}

    - name: 'Bundle Artifacts for Diagnostics'
      if: ${{ always() }}
      uses: trevorsandy/povray/.github/actions/git_bundle_ignored@gh-actions-raytracer-v4
      with:
        name: artifact_diag_unix.tar.gz

    - name: 'Build'
      uses: trevorsandy/povray/.github/actions/unix_make@gh-actions-raytracer-v4

    - name: 'Build Check'
      if: ${{ success() }}
      uses: trevorsandy/povray/.github/actions/unix_make@gh-actions-raytracer-v4
      with:
        make-target: check

    - name: 'Upload Artifacts for Diagnostics'
      if: ${{ failure() }}
      uses: actions/upload-artifact@v4
      with:
        name: artifact_diag_${{ matrix.os }}_${{ matrix.c-compiler }}
        path: artifact_diag_${{ matrix.os }}_${{ matrix.c-compiler }}.tar.gz

  build_windows:
    # if: ${{ false }} # uncomment to disable
    name: 'build-${{ matrix.runner }} ${{ matrix.platform }}'

    runs-on: ${{ matrix.runner }}
    strategy:
      fail-fast: false
      matrix:
        runner: [windows-2022]
        platform: [Win32, x64]
        include:
        - platform: Win32
          toolset: v141
          compatibility: ''
          msbuild-options: ''
        - platform: x64
          toolset: v143
          compatibility: ''
          msbuild-options: ''

    steps:

    - name: 'Check out Repository'
      uses: actions/checkout@v4

    - name: 'Add MSBuild to PATH'
      uses: microsoft/setup-msbuild@v2

    - name: 'Build'
      uses: trevorsandy/povray/.github/actions/windows_build@gh-actions-raytracer-v4
      with:
        pov-ray-build-id: gh+vs2022+${{ matrix.platform }}+${{ github.run_number }}
        version-base: 3.8
        solution: vs2015
        configuration: Release
        platform: ${{ matrix.platform }}
        toolset: ${{ matrix.toolset }}
        compatibility: ${{ matrix.compatibility }}
        msbuild-options: ${{ matrix.msbuild-options }}

    - name: 'Build Check'
      if: ${{ success() }}
      uses: trevorsandy/povray/.github/actions/windows_check@gh-actions-raytracer-v4
      with:
        version-base: 3.8
        solution: vs2015
        platform: ${{ matrix.platform }}

    - name: 'Upload Artifacts for Diagnostics'
      if: ${{ failure() }}
      uses: actions/upload-artifact@v4
      with:
        name: artifact_diag_${{ matrix.runner }}_${{ matrix.platform }}
        path: artifact_diag_${{ matrix.runner }}_${{ matrix.platform }}.zip